# Part 0

Download the following files:

[Titanic Full](https://drive.google.com/file/d/1jv3Ctntzb07jqmbfTFKZeS699j0jBjjE/view?usp=share_link)

[Titanic Training](https://drive.google.com/file/d/1WNatBun5NcGLtZrzBgb15ima4Euwep9B/view?usp=share_link)

[Titanic Test](https://drive.google.com/file/d/1T0XwZ7VRqY5tAarbdvLEGuYCC4fVR0BY/view?usp=share_link)

Load the three dataframes into memory, naming them titanic, titanic_train, and titanic_test.

This exercise will be auto-graded, so please make sure to follow the instructions **exactly**.

In [1]:
import pandas as pd
import numpy as np
titanic=pd.read_csv('titanic.csv')
titanic_train=pd.read_csv('titanic_train.csv')
titanic_test=pd.read_csv('titanic_test.csv')

# Part 1

Write code that takes `titanic` and uses pd.get_dummies() to one-hot encode the "Sex" column, and add those columns to the titanic dataframe. Print the head of the new dataframe. Once we are done with this step, we won't use the `titanic` dataframe for anything else.

In [2]:
titanic = pd.concat([titanic,pd.get_dummies(titanic['Sex'])], axis=1, join='inner')
titanic.head()


Age Cabin Embarked     Fare  \
0  22.0   NaN        S   7.2500   
1  38.0   C85        C  71.2833   
2  26.0   NaN        S   7.9250   
3  35.0  C123        S  53.1000   
4  35.0   NaN        S   8.0500   

                                                Name  Parch  PassengerId  \
0                            Braund, Mr. Owen Harris      0            1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0            2   
2                             Heikkinen, Miss. Laina      0            3   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      0            4   
4                           Allen, Mr. William Henry      0            5   

   Pclass     Sex  SibSp  Survived            Ticket Title  Family_Size  \
0       3    male      1       0.0         A/5 21171    Mr            1   
1       1  female      1       1.0          PC 17599   Mrs            1   
2       3  female      0       1.0  STON/O2. 3101282  Miss            0   
3       1  female      1       1.0            113803   Mrs            1   
4       3    male      0       0.0            373450    Mr            0   

   female   male  
0   False   True  
1    True  False  
2    True  False  
3    True  False  
4   False   True

# Part 2

Train a [decision tree](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html) using titanic_train. Print out the % accuracy of running the `predict()` function over `titanic_train["Survived"]`. (Basically, we're predicting the decision tree's accuracy on the training set.)

**For all classifiers, you must include the argument random_state=0 upon initilzation, or the auto-grader won't work. This will result in a 10% penalty.**

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
clf = DecisionTreeClassifier(random_state=0)

x = ['female', 'male', 'Age', 'Fare', 'Family_Size', 'Pclass']
target = 'Survived'
x_train = titanic_train[x]
target_train = titanic_train[target]

clf.fit(x_train, target_train)

train_predictions = clf.predict(x_train)

accuracy_score(target_train, train_predictions)

0.98125

# Part 3

Print out the trained decision trees accuracy on the test set.

In [4]:
x_train_test = titanic_test[x]
target_train_test = titanic_test[target]

test_predictions = clf.predict(x_train_test)
accuracy_score(target_train_test, test_predictions)

0.8241758241758241

# Part 4

Going forward, you will not need titanic_test for anything.

Using [this function](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html), print out the cross-val score for your decision tree with k=10 using **only the training set**. This will be an array of ten numbers.

In [5]:
from sklearn.model_selection import cross_val_score
cross_val_score(clf, x_train, target_train, cv=10)

array([0.75  , 0.725 , 0.7875, 0.7375, 0.8   , 0.7875, 0.75  , 0.8   ,
       0.7125, 0.75  ])

# Part 5

Print out the ten-fold cross-valdiation results for a [support vector machine](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html) over the training set.

In [6]:
from sklearn.svm import SVC
svm = SVC(random_state=0)
cross_val_score(svm, x_train, target_train, cv=10)

array([0.6125, 0.6   , 0.6375, 0.75  , 0.7   , 0.6625, 0.675 , 0.725 ,
       0.725 , 0.7   ])

# Part 5

Print out the ten-fold cross-valdiation results for a [random forest](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html) over the training set.

In [7]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
cross_val_score(rf, x_train, target_train, cv=10)

array([0.7625, 0.8   , 0.8125, 0.775 , 0.8375, 0.8375, 0.825 , 0.8375,
       0.7625, 0.825 ])